### ISSUE TITLE
Error: Model "Customer" uses unknown mixin: ChangeHistory

### ISSUE THREAD

**Issue by mersahin** [alexkander/loopback-changes-history-mixin#6]
loopback version: 3.28
Configration is OK 

{
  "_meta": {
    "sources": [
      "loopback/common/models",
      "loopback/server/models",
      "../common/models",
      "./models"
    ],
    "mixins": [
      "loopback/common/mixins",
      **"../node_modules/loopback-changes-history-mixin",**
      "../common/mixins"
    ]
  }
}

{
  "name": "Person",
  "properties": {
    "name": "string",
    "email": "string",
    "status": "string",
    "description": "string"
  },
  **"mixins": {
    "ChangeHistory": true
  }**
}

BUT

`Error: Model "Person" uses unknown mixin: ChangeHistory
    at MixinProvider.applyMixin (/Users/Desktop/backend/node_modules/loopback-datasource-juggler/lib/mixins.js:50:13)
    at ModelBuilder.defineClass [as define] (/Users/Desktop/backend/node_modules/loopback-datasource-juggler/lib/model-builder.js:649:27)
    at Function.ModelClass.extend (/Users/Desktop/backend/node_modules/loopback-datasource-juggler/lib/model-builder.js:447:35)
    at Registry.createModel (/Users/Desktop/backend/node_modules/loopback/lib/registry.js:122:27)
    at /Users/Desktop/backend/node_modules/loopback-boot/lib/executor.js:245:24
    at Array.forEach (<anonymous>)
    at defineModels (/Users/Desktop/backend/node_modules/loopback-boot/lib/executor.js:229:23)
    at setupModels (/Users/Desktop/backend/node_modules/loopback-boot/lib/executor.js:197:3)
    at execute (/Users/Desktop/backend/node_modules/loopback-boot/lib/executor.js:40:3)
    at bootLoopBackApp (/Users/Desktop/backend/node_modules/loopback-boot/index.js:154:3)
    at Object.<anonymous> (/Users/Desktop/backend/app.js:34:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Waiting for the debugger to disconnect...
`

**Comment by alexkander** [comment]
Hi,

There was a mistake in the readme with the name of the mixin. The right mixin name is "ChangesHistory".
```js
{
  "name": "Person",
  "properties": {
  "name": "string",
  "email": "string",
  "status": "string",
  "description": "string"
  },
  "mixins": {
    "ChangeHistory": true // <<<< Change for "ChangesHistory": true
  }
}
```

Regards.
